---
- name: test-playbook

  hosts: localhost

  remote_user: ubuntu

  become: yes

  become_method: sudo

  tasks:

    - name: Download sonarqube binary

      shell:

        cmd: wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.6.zip

        chdir: /tmp

    - name: Unzip sonarqube binary

      shell:

        cmd: unzip sonarqube-6.7.6.zip

        chdir: /tmp

    - name: Move unzipped sonarqube to /opt

      shell:

        cmd: mv sonarqube-6.7.6 /opt

        chdir: /tmp

    - name: start sonar

      shell:

        cmd: ./sonar.sh start

        chdir: /opt/sonarqube-6.7.6/bin/linux-x86-64/
