---
# tasks file for install-maven

- name: create maven directory
  file:
    path: /opt/apache-maven-3.3.9
    state: directory
   
- name: Downloading Maven Binaries

  get_url:

    url: http://apache.mirror.digitalpacific.com.au/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz

    dest: '/opt/apache-maven-3.3.9-bin.tar.gz'



- name: Unarchive Maven Binaries

  unarchive:

    src: '/opt/apache-maven-3.3.9-bin.tar.gz'

    dest: '/opt/apache-maven-3.3.9'

    copy: no

- name: Install maven
  command: 'sudo update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-3.3.9/bin/mvn 1001'

- name: Cleaning Up

  file:

    state: absent

    path: '/opt/apache-maven-3.3.9-bin.tar.gz'

