---
# tasks file for install-sonarqube
    - name: Install java jdk
      apt:
        pkg: default-jdk
        state: present  
        
    - name: Download and unarchive sonarqube binary  
      unarchive:      
        src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.6.zip        
        dest: /tmp     
        remote_src: yes
        
    - name: Move unarchived sonarqube to /opt
      command: mv sonarqube-6.7.6 /opt    
      args:
        chdir: /tmp
        creates: /opt/sonarqube-6.7.6

    - name: changing ownership
      file:
        path: /opt/sonarqube-6.7.6
        owner: "ubuntu"
        group: "ubuntu"
        recurse: yes        
        state: directory
        mode: '0755'
      
    - name: start sonar
      become: yes
      become_user: ubuntu
      shell:
        cmd: ./sonar.sh start
        chdir: /opt/sonarqube-6.7.6/bin/linux-x86-64
