---
# tasks file for install-sonarqube
    - name: Install java jdk
      become: yes
      become_user: ubuntu
      apt:
        pkg: default-jdk
        state: present  
        
    - name: Download and unarchive sonarqube binary
      become: yes
      become_user: ubuntu    
      unarchive:      
        src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.6.zip        
        dest: /tmp     
        remote_src: yes
        owner: "ubuntu"
        group: "ubuntu"
        
    - name: Move unarchived sonarqube to /opt
      become: yes
      become_user: ubuntu
      command: mv sonarqube-6.7.6 /opt    
      args:
        chdir: /tmp
        creates: /opt/sonarqube-6.7.6
        
    - name: start sonar
      become: yes
      become_user: ubuntu
      shell:
        cmd: ./sonar.sh start
        chdir: /opt/sonarqube-6.7.6/bin/linux-x86-64
