---
# tasks file for install-docker

    - name: ensure repository key is installed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present


    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: ensure docker and dependencies are installed
      apt: name=docker-ce state=latest



    - service: name=docker state=restarted
